controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0



# arm_controller:
#   ros__parameters:
#     joints:
#       - shoulder_pan
#       - shoulder_lift
#       - elbow_flex
#     command_interfaces: [position]
#     state_interfaces: [position, velocity]
